language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- cd $TRAVIS_BUILD_DIR/functions && npm install
- cd $TRAVIS_BUILD_DIR && npm install firebase-tools -g
script:
- cd $TRAVIS_BUILD_DIR && yarn run build
- firebase deploy --token $FIREBASE_TOKEN
env:
  global:
    secure: "fQPZHtiPxVmKmAMVmk2IahA1gVvRGLOpVZ0vfkzVZmSOvolFUn1G+H7GK+D8XcAJbRC43CAmmWd5hL8J8e4pl4X4wmb/OOeCbCG9bE+w6RGRTacHrMTu05oHM0UN5V1cOz9K/xFnpcsxU1KIzTKHZHtM/zTY3sVBWymlRgGH7kn7MySvKxoa/Hptv6bLQzpY1gCU/CqtJoYq68+7eUICRIWgXXiFWKG5ex56TMF8NYwqMwBXF0cuEdBQXQPBppNjPmZTr8C8L2NQMCKtgYZy+wzlV7UBqVHoSu80YLEXgoIeC4jxEiXPL1RwXPBDT0a0iYxxp+JSsv2xIx1srp83lJB0uaV/qwkH5huLEcf7rr3q24DaqjBrn+uYE7uJYs7JtWSP/PawBiLxuUbfSAM4iwYHGzMstJos7nmitqzyvW3DH+m81LqYaaU570pZT42IXpRUqhZSiXVHR5Oj5OzEW8Dcj10Ye1UBxe4H0/g5TKMW5itrzWFmmJJhv5pqmrZ9jWBzujhfb7UqbuLHhnvR7WPBwDpO9T9HeS0rRT6xl77q4Xqm9N/dqUNTUXDKzJAhxrpvQe4FddAyHnjT+xcCo/gl99QSNlcLvO/HYsvWRe9/45aaZ6ZaarQa6yA0AqFUI8Dmxj6WbNu7rwxpMeHGUDx1kd4Pj4EZ8Zey0IOkpzA="
    
    secure: "bosNbsUKzgQ6fZO9zpvVR7Tx7dSAE07UdSL9W/Ea3lpcN3wliGlmWI6hOZ4B0ExgjvuDE3ckrtU27UmTezmJQ83CflnCA8JbXbN5fY4OzKjihHaIO6VYmRe9YH8i/VxBecvAAi8ikaTWE/Ez+jIpzUk4F7VDyF73dauBKZAXqUKcMxl7FpyS0mWEQC+GJDgHDBtg2SPf5qv3o2yG6+sQpwLNw3dhOOHCmmIQ+jAmXmnYIwsI1v6WOI/EXdmeYqf4ynF3YRNMTu8zoiRojEK2v56fDgXberxj8LobvDQoyC5fsNKf1hqq9J3DW4dFoEKj1ZI1NpnMRp52WHLKiUQLqE8UWxP7f6LVtfvkxp9eq+IZ0eoGlkA86PLJSHeU0cQ4521luG9UTyWeQvplgcaZBcUvUS5UbESFP29bRUYjnsEHERySHr/UFDYtw1yziNLd/NdbBYT9ly4+kHlGCT5tqF4H08GdjQP31dvhsad/VZjVFTyiJzH5XPG8NKwkNb+/kzFceanwJuceEH/4AOs99n4PNpYhA9mYnDX6sZpbXtfVSm9DA2N09GI3eu8Bqnh9pQoHptjTdK49MNLvf0qsY4zzxYqcTNYCS7tBUGlJUrkRi8NmPqy0eYLGIJQ97oOcfNGY5UJqlmK0lLhwrURkO2YFpsRj7gSa0bVlZjsNZwQ="
    - REACT_APP_AUTH_DOMAIN=yadahreg-6f904.firebaseapp.com
    - REACT_APP_DATABASE_URL=https://yadahreg-6f904.firebaseio.com
    - REACT_APP_PROJECT_ID=yadahreg-6f904
    - REACT_APP_STORAGE_BUCKET=yadahreg-6f904.appspot.com
    - REACT_APP_MESSAGING_SENDER_ID=465435362762
    - REACT_APP_APP_ID=1:465435362762:web:50a0e35f742dfc97
