language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  #- npm test
  - cd functions && npm install
  - cd $TRAVIS_BUILD_DIR && yarn run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "rF4VrSl8MeRPV/TGP1DJmt1Cq4RneAdL996v/adpLLpliz2Z5CXjAc1klxu0EzHrqNgjdBhQFsXRKDDFzrUKrvrFzgI0uLigv2Lfaxu0pD5Q8DwEbRyIr82CUFkjv1p4Dvya9lLGe1VQNwI/+W+TS45hGilNXe/N0/Kps7BpuYluMLLEfXc/CWjZdwUCsfP8VyTdOLQ7rMKMec4gtJyC241+bUYI4zEdnFFZyMXx2smNeMth45IzO77kflKUFcgNoSarQ3BLcYA57tGGoFIPuLqaEbj9TPU71v/1C57Ys7WcVfOu96CC5rnLAfNRrYDLP9da431+Y6l0fDVNWHuytGmK+S8PiFszwID8tThna+L2yTcO3IBAfDvSvMVUzflkDNHbjOg0gd8yUz2iB8C01btTBU74EKjxH+vjI/G/bhDJm4/7Zjmn0usqsjgZhRPNfe0yR2B6VdgSBoM2Fimm5M5MMQFuydDC4BQKKaBYRwU8B3sNAIywO27KjS89EagKkOpDWVUYZcivc/X5a3T4lrW2RnJdzGQQv3YorgQhX9wHEImmb4+mQINyTm95WZdI5e+gsaLucxY1cFI6fTbMZMS19A9xrqMwjFRRytMNDjT+WoWmAgvf39T+MBrg1sVhuVjnMF0FMnNaijNFpe8lWSx93wtflw9/wFrure4nfBE="
  on:
    branch: master