name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      run_configuration: ${{ fromJSON('["test", "prod"]')[startsWith(github.ref, 'refs/tags/v')] }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install dependencies
        run: yarn
      - name: Install dependencies for functions
        working-directory: ./functions
        run: npm install
      
      - name: Build SPA
        run: yarn run build:${{ env.run_configuration }}

      - name: Use correct Firebase environment
        run: firebase use ${{ env.run_configuration }}
      
      - name: Deploy application
        run: firebase deploy
